services:
  gateway:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  h5:
    pull_policy: always
    environment:
      LOG_LEVEL: debug
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api:
    pull_policy: always
    environment:
      LOG_LEVEL: debug
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    pull_policy: always
    environment:
      LOG_LEVEL: debug
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
